apiVersion: v2
appVersion: v7.5.176
description: Unifi chart for Kubernetes
home: https://github.com/k8sonlab/publiccharts/tree/main/charts/unifi
icon: https://prd-www-cdn.ubnt.com/static/favicon-152.png
keywords:
- ubiquiti
- unifi
name: unifi
type: application
version: 0.1.12
